package dimitrov.sum;

public class DocumentInitializationException extends Exception {

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 6870487711492470133L;

	public DocumentInitializationException(Throwable cause) {
		super(cause);
	}

	public DocumentInitializationException(String message, Throwable cause) {
		super(message, cause);
	}

	public DocumentInitializationException(String message, Throwable cause,
			boolean enableSuppression, boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
	}

}
